parameters:
    # Permet de passer cette url en tant que variable d'environnement
    env(DATABASE_URL): ''
    # mysql://utilisateur:mot_de_passe@ip:un_port/nom_de_la_base_de_données
doctrine:
    dbal:

        driver:
        server_version:
        charset:


        url: '%env(resolve:DATABASE_URL)%'


        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
